replicaCount: 1

refs:
  appPort: &appPort 5100

image:
  project: greeding-service
  name: service-b
  tag: stable
  pullPolicy: Always
  port: *appPort

service:
  type: ClusterIP
  targetPort: *appPort
  port: *appPort

secret:
  name: mysecret