replicaCount: 1

refs:
  appPort: &appPort 5100

image:
  repository: gcr.io/devdojo-2019-april-1/service-b
  tag: 0.5.0
  pullPolicy: Always
  port: *appPort

service:
  type: ClusterIP
  targetPort: *appPort
  port: *appPort

secret:
  name: mysecret