replicaCount: 1

refs:
  appPort: &appPort 5050

image:
  project: greeding-service
  name: service-a
  tag: stable
  pullPolicy: Always
  port: *appPort

service:
  type: LoadBalancer
  targetPort: *appPort
  port: *appPort

configMap:
  name: my-config-map