replicaCount: 1

refs:
  appPort: &appPort 5050

image:
  repository: gcr.io/devdojo-2019-april-1/service-a
  tag: 0.5.0
  pullPolicy: Always
  port: *appPort

service:
  type: LoadBalancer
  targetPort: *appPort
  port: *appPort

configMap:
  name: my-config-map